### ISSUE TITLE
[Monthly]: test

### ISSUE THREAD

**Issue by prowe** [prowe/checklists#1]
### Tasks

- [X] Ask team if allocation is on-target
- [ ] Determine if schedule is working well
- [ ] Are there any individuals at the partner that are involved in the project that I need to build a relationship with?
