### ISSUE TITLE
Dyna Trace

### ISSUE THREAD

**Issue by prowe** [prowe/checklists#2]
### Tasks

- [X] Determine how big the meeting is
- [X] What is my personal goal for the meeting
- [X] Do I have enough time?
- [X] What are each teammates roles in the meeting.
- [X] Is there a defined agenda for the meeting
